package com.philihp.weblabora.model;

import com.google.common.collect.ImmutableMap;
import com.philihp.weblabora.model.Scorecard.PlayerScore;
import com.philihp.weblabora.model.building.*;
import org.junit.Before;
import org.junit.Test;

import java.util.Map;
import java.util.Map.Entry;

import static org.hamcrest.Matchers.*;
import static org.junit.Assert.assertThat;

/**
 * Runs through game 53955 and checks ending board.
 */
public class Game46615Test {

  Board board;

  @Before
  public void setUp() throws Exception {
    board = new Board();
    MoveProcessor.processMove(board, "config PLAYERS 4");
    MoveProcessor.processMove(board, "config LENGTH LONG");
    MoveProcessor.processMove(board, "config COUNTRY IRELAND");
    MoveProcessor.processMove(board, "start");
    MoveProcessor.processMove(board, "fell_trees1 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I03 3 1");
    MoveProcessor.processMove(board, "use I03 Pn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR3 Pn");
    MoveProcessor.processMove(board, "buy_plot 0 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build I09 3 0");
    MoveProcessor.processMove(board, "use I09 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW3 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I08 -1 0");
    MoveProcessor.processMove(board, "use I08 Be *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G13 3 0");
    MoveProcessor.processMove(board, "use G13 PnPn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I11 -2 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G07 0 0");
    MoveProcessor.processMove(board, "use G07 PtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I08 Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 ShJo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I03 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I05 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I11");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I09");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract LW2 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use LW2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 3 0 PtWoGnSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 1 0 ShGnPtWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S04 -1 1 WoPtBeBe");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 3 1 ShPnCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I08 Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I09");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW3 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I04 2 0");
    MoveProcessor.processMove(board, "use I04 GnGnGnGnGnGnGnGnGnGnGnGn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G07 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G07 PtPtPtPtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 0 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build I17 3 1");
    MoveProcessor.processMove(board, "use I17 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S01 2 0 WoPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S01 1 0 PnSwSw");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S01 0 1 PnWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 0 0 MtSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I09");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I03 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I14 1 1");
    MoveProcessor.processMove(board, "use I14 Gn Be *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot 0 MOUNTAIN");
    MoveProcessor.processMove(board, "build G22 6 0");
    MoveProcessor.processMove(board, "use G22 Jo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G12 3 0");
    MoveProcessor.processMove(board, "use G12 ShShShShShPtPtPt *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G22 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 2 PLAINS");
    MoveProcessor.processMove(board, "build G02 4 2");
    MoveProcessor.processMove(board, "use G02 SwGnHo Gn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district -1 PLAINS");
    MoveProcessor.processMove(board, "fell_trees0 -1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 2 HILLS");
    MoveProcessor.processMove(board, "build I15 4 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot 2 MOUNTAIN");
    MoveProcessor.processMove(board, "use I09");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 0 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I03 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I04 GnGnGnGnGnGnGnGnGnGnGnGnGnGnGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G22 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G22");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I15 ClClClClCl WoWoWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract I05 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use I05 GnHoGnHoGnHoGnHoGnHoGnHoGnHoGnHoGnHoGnHoGnHoGnHo Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 0 -1 BeCoCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 0 1 WoBe");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 5 2 CoCoShShSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 1 2 BeSwSw");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I29 1 -1");
    MoveProcessor.processMove(board, "use I29 2 0 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot 2 COAST");
    MoveProcessor.processMove(board, "build G26 -1 3");
    MoveProcessor.processMove(board, "use G26 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I09");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I23 3 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 2 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 2 HILLS");
    MoveProcessor.processMove(board, "use I09");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G22 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G22");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G07 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G07 PtPtPtPtPtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S07 2 2 SwSwSwSwSwSwSwSwSwSwSwSwSwSwSwSwSwSwBeBeBe");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 2 -1 WoShShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 0 2 CoCoShShHo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 3 2 ShShGnPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees0 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district -2 PLAINS");
    MoveProcessor.processMove(board, "build I37 2 0");
    MoveProcessor.processMove(board, "use I37 Bo *");
    MoveProcessor.processMove(board, "buy_district 2 PLAINS");
    MoveProcessor.processMove(board, "buy_plot -1 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I17 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 3 HILLS");
    MoveProcessor.processMove(board, "fell_trees2 2 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I21 1 1");
    MoveProcessor.processMove(board, "use I21 HoWoPtHoWoPtHoWoPtHoWoPtHoWoPtHoWoPtHoWoPt *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I23 PnPn");
    MoveProcessor.processMove(board, "build G39 2 -2");
    MoveProcessor.processMove(board, "use G39 CoCoCoCo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I31 -1 2");
    MoveProcessor.processMove(board, "use I31 CoCoCo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGnGnGn");
    MoveProcessor.processMove(board, "build G19 0 1");
    MoveProcessor.processMove(board, "use G19 ShShShShSwSwSwSw *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I15 GnGnGnGnGn ShShSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G28 6 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I24 3 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G18 3 2");
    MoveProcessor.processMove(board, "use G18 SnClClClCoWo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I27 4 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I24 PnBeWhBeWhBeWh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGnGnGnGnGnGnGnGn");
    MoveProcessor.processMove(board, "build G01 3 2");
    MoveProcessor.processMove(board, "use G01 *");
    MoveProcessor.processMove(board, "use G19 ShSwShSwShSwShSwShSwShSwShSwShSwShSw");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 ShJo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Ni");
    MoveProcessor.processMove(board, "use I24 PnBeWhBeWhBeWh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I23 PnPn");
    MoveProcessor.processMove(board, "build I32 2 2");
    MoveProcessor.processMove(board, "use I32 WoShSwGnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G28 PnPn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S07 1 1 MtMtMtCoCoCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract I15 Wh");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use I15 GnGnGnGnGn PtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees0 -2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 3 HILLS");
    MoveProcessor.processMove(board, "work_contract G22 Wh");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G22");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S08 4 2 MtMtMtMtShShShShShCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract I05 Wh");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use I05 GnHoGnHoGnHoGnHoGnHo Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build I40 1 2");
    MoveProcessor.processMove(board, "use I40 *");
    MoveProcessor.processMove(board, "use I30 MtMtMtMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I40");
    MoveProcessor.processMove(board, "use I30");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I24 PnBeWhBeWhBeWh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I20 0 -2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S08 4 3 CoMtMtMtMtBePnPnPnWh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S07 5 3 CoPtPtPtBeMtShShPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 0 2 PtPtPtBe");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S07 1 -2 CoWoWoWoWoWoWoShShShShShShShSh");
    MoveProcessor.processMove(board, "commit");
  }

  @Test
  public void testEndingScores() throws WeblaboraException {
    assertThat(board.isGameOver(), is(true));
  }
}
