package com.philihp.weblabora.model;

import com.google.common.collect.ImmutableMap;
import com.philihp.weblabora.model.Scorecard.PlayerScore;
import com.philihp.weblabora.model.building.*;
import org.junit.Before;
import org.junit.Test;

import java.util.Map;
import java.util.Map.Entry;

import static org.hamcrest.Matchers.*;
import static org.junit.Assert.assertThat;

/**
 * Runs through game 53955 and checks ending board.
 */
public class Game20430Test {

  Board board;

  @Before
  public void setUp() throws Exception {
    board = new Board();
    MoveProcessor.processMove(board, "config PLAYERS 2");
    MoveProcessor.processMove(board, "config LENGTH SHORT");
    MoveProcessor.processMove(board, "config COUNTRY FRANCE");
    MoveProcessor.processMove(board, "start");
    MoveProcessor.processMove(board, "use LR3 Jo");
    MoveProcessor.processMove(board, "buy_district -1 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G13 3 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F09 3 1");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use LG2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G07 0 1");
    MoveProcessor.processMove(board, "use G07 PtPtPt *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 0 -1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use LG3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 2 PLAINS");
    MoveProcessor.processMove(board, "fell_trees 0 2 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 3 -1 CoShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S01 1 2 WoGp");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G02 3 2");
    MoveProcessor.processMove(board, "use G02 ShPtGn Pn");
    MoveProcessor.processMove(board, "buy_plot 1 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F04 4 -1");
    MoveProcessor.processMove(board, "use F04 GnGnGnGnGn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G12 3 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F05 0 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract F05 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use F05 FlFlFlFlFlCoCo BrBr");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use LG3 Jo");
    MoveProcessor.processMove(board, "buy_district 3 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G02 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G02 PnWoCl Wo");
    MoveProcessor.processMove(board, "buy_plot -1 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G19 2 0");
    MoveProcessor.processMove(board, "use G19 ShShShShShSwSwSwSwSw *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 0 1 ShShShGp");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S04 -1 0 CoMtBr");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F08 1 1");
    MoveProcessor.processMove(board, "use F08 WoPtPnCl");
    MoveProcessor.processMove(board, "buy_plot -1 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G12 MtMtPtPtWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use LG3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract LR2 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use LR2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR3 Jo *");
    MoveProcessor.processMove(board, "buy_district 2 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F23 2 2");
    MoveProcessor.processMove(board, "use F23");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F11 -1 -1");
    MoveProcessor.processMove(board, "use F11 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G13 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F14 4 3");
    MoveProcessor.processMove(board, "use F14");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F25 -1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 0 -1 WoMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S04 -1 0 PtWoBrPnPnPnPnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G07 PtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F23");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F33 -1 -1");
    MoveProcessor.processMove(board, "use F33 PtWo Mt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 1 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F15 3 0");
    MoveProcessor.processMove(board, "use F15 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR3");
    MoveProcessor.processMove(board, "buy_plot 1 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F23");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build F21 1 3");
    MoveProcessor.processMove(board, "use F21 GpGpGpGpGpGpGpGp Wn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract F14 PnPn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use F14");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G01 4 2");
    MoveProcessor.processMove(board, "use G01 *");
    MoveProcessor.processMove(board, "use F21 GpGpGpGpGpGpGp Wn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 2 3 PtPtPtMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot -1 MOUNTAIN");
    MoveProcessor.processMove(board, "settle S06 5 -1 CoCoMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot 2 MOUNTAIN");
    MoveProcessor.processMove(board, "build G22 6 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G22");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G12 BrBrShShCoWoWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G28 6 -1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F38 0 0");
    MoveProcessor.processMove(board, "use F38 1 0 2 0 0 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGn");
    MoveProcessor.processMove(board, "build F30 2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR3 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot 1 MOUNTAIN");
    MoveProcessor.processMove(board, "build F40 5 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F30");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district -1 PLAINS");
    MoveProcessor.processMove(board, "convert GnGn");
    MoveProcessor.processMove(board, "build F20 1 -1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F24 5 0");
    MoveProcessor.processMove(board, "use F24 BrWn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F20 MtWn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot 3 COAST");
    MoveProcessor.processMove(board, "build F36 -1 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G22 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G22");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use LG2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build F17 3 3");
    MoveProcessor.processMove(board, "use F17 PnPnPn Bo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G39 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F40");
    MoveProcessor.processMove(board, "use G18 ClClClSnCoWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G07 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G07 PtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G28 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S07 1 0 CoCoCoMtMtMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGn");
    MoveProcessor.processMove(board, "build G34 3 2");
    MoveProcessor.processMove(board, "use G34 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract LG1 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use LG1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F33 Co Mt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G41 4 2");
    MoveProcessor.processMove(board, "use G41 Ni RqOr");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G22 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G22");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G26 -1 2");
    MoveProcessor.processMove(board, "use G26 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "use G02 GnSwBo Wo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G28 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S05 -1 2 MtWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract F20 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use F20 WnShShShFl");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot -3 MOUNTAIN");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "use G26");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F20 MtGnGnWn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G28 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S02 0 3 CoMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G26");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F27 5 -2");
    MoveProcessor.processMove(board, "use F27 *");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S03 2 2 ShShGnGnFl");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 4 HILLS");
    MoveProcessor.processMove(board, "cut_peat 0 4");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use LG2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 0 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G18 5 2");
    MoveProcessor.processMove(board, "use G18 ClClClSnWoWoWoWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G07 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G07 PtPtPtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "use F25 WoClPnPtSwGnShGpCoMtWnBoPo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build F03 -1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F33 Co Wn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "use F25 WoClNiPnPtGnSwShGpCoMtBoWn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR3");
    MoveProcessor.processMove(board, "buy_district 3 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGnGn");
    MoveProcessor.processMove(board, "build F37 3 3");
    MoveProcessor.processMove(board, "use F37 WoWoWoSwSwSw *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract F27 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use F27 Wn");
    MoveProcessor.processMove(board, "use F25 WoClSnSwPnPtShGpCoMtBoPoOr");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract F36 PnPn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use F36 Or Or");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use G02 WoPtCo Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G28 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S08 3 4 ShShShShShShShShShShShShShPnPnGpGpCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G34");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F32 2 3");
    MoveProcessor.processMove(board, "commit");
  }

  @Test
  public void testEndingScores() throws WeblaboraException {
    assertThat(board.isGameOver(), is(true));
  }
}
