package com.philihp.weblabora.model;

import com.google.common.collect.ImmutableMap;
import com.philihp.weblabora.model.Scorecard.PlayerScore;
import com.philihp.weblabora.model.building.*;
import org.junit.Before;
import org.junit.Test;

import java.util.Map;
import java.util.Map.Entry;

import static org.hamcrest.Matchers.*;
import static org.junit.Assert.assertThat;

/**
 * Runs through game 53955 and checks ending board.
 */
public class Game46808Test {

  Board board;

  @Before
  public void setUp() throws Exception {
    board = new Board();
    MoveProcessor.processMove(board, "config PLAYERS 4");
    MoveProcessor.processMove(board, "config LENGTH LONG");
    MoveProcessor.processMove(board, "config COUNTRY IRELAND");
    MoveProcessor.processMove(board, "start");
    MoveProcessor.processMove(board, "use LR3");
    MoveProcessor.processMove(board, "buy_plot 0 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build I09 3 0");
    MoveProcessor.processMove(board, "use I09 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I03 3 1");
    MoveProcessor.processMove(board, "use I03 Pn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB3 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I08 -1 0");
    MoveProcessor.processMove(board, "use I08 Be *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G13 3 0");
    MoveProcessor.processMove(board, "use G13 PnPn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I11 -2 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I03 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I11");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I08 Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I09");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I11");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG3 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I10 3 1");
    MoveProcessor.processMove(board, "use I10 *");
    MoveProcessor.processMove(board, "use LB2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract White Pn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use I03 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 1 0 ShShShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S01 1 0 GnWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S04 -1 1 PtWoBeShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S01 3 1 GnPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I08 Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG3 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I14 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I04 0 0");
    MoveProcessor.processMove(board, "use I04 GnGnGnGnGnGnGnGnGnGnGnGnGnGnGnGn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I11");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I14 GnGn Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 2 PLAINS");
    MoveProcessor.processMove(board, "use LW3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 2 0 PtPtShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 1 1 BeWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 1 2 SwSwSwSwSwSwShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 0 1 BePt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot 0 MOUNTAIN");
    MoveProcessor.processMove(board, "build G22 6 0");
    MoveProcessor.processMove(board, "use G22 Jo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I10");
    MoveProcessor.processMove(board, "use LB2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Blue Pn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I10");
    MoveProcessor.processMove(board, "use LB3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I08 Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I09");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 2 PLAINS");
    MoveProcessor.processMove(board, "use LB3 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Blue Pn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Green Pn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G22 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I03 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G12 3 0");
    MoveProcessor.processMove(board, "use G12 BeBePtPtPt *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G07 0 0");
    MoveProcessor.processMove(board, "use G07 PtPtPtPtPt *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I10");
    MoveProcessor.processMove(board, "use LB3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW3 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I11");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I09");
    MoveProcessor.processMove(board, "buy_plot 2 MOUNTAIN");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I15 4 2");
    MoveProcessor.processMove(board, "use I15 PnPnPnPnPn ShShSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot 2 COAST");
    MoveProcessor.processMove(board, "build G26 -1 3");
    MoveProcessor.processMove(board, "use G26 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Ni");
    MoveProcessor.processMove(board, "work_contract Red Pn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use I08 Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Green Pn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G22");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I11");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 2 2 GnGnGnGnGnSwSw");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 0 0 NiPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 5 2 BeWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 0 1 PtPtPtShShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I03 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Green Pn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G07 PtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 2 HILLS");
    MoveProcessor.processMove(board, "work_contract Red Pn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use I08 Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot 1 MOUNTAIN");
    MoveProcessor.processMove(board, "build G18 5 1");
    MoveProcessor.processMove(board, "use G18 ClClClSnPtPt *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I17 3 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I31 -1 2");
    MoveProcessor.processMove(board, "use I31 CoCoCo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I05 1 1");
    MoveProcessor.processMove(board, "use I05 GnHoGnHoGnHoGnHoGnHoGnHoGnHoGnHoGnHoGnHoGnHoGnHoGnHo Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 2 HILLS");
    MoveProcessor.processMove(board, "cut_peat 0 2 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I30 5 1");
    MoveProcessor.processMove(board, "use I30");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I14 GnGn Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G22");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 1 2 PtWoShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S07 0 1 BeBeBePtPtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 1 0 CoShPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S07 5 3 CoCoCoBeBeMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I15 GnGnGnGnGn PtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 3 PLAINS");
    MoveProcessor.processMove(board, "build I21 1 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGnGnGnGnGnGn");
    MoveProcessor.processMove(board, "build G19 3 2");
    MoveProcessor.processMove(board, "use G19 ShSwShSwShSwShSwShSwShSwShSwShSw *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I21 HoPtWoHoPtWoHoPtWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I38 0 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G01 5 0");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "convert GnGnGnGnGnGnGnGn");
    MoveProcessor.processMove(board, "use G19 ShSwShSwShSwShSwShSwShSwShSwShSw");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Green PnPn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G07 PtPtPtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Blue Wh");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 2 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees2 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Green PnPn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G22");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract GREEN Wh");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G07 PtPtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G28 6 2");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S08 4 2 MtMtMtMtMtMtCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G18 ClClClSnCoWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I24 3 3");
    MoveProcessor.processMove(board, "use I24 BeWhBeWhBeWhPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G39 1 2");
    MoveProcessor.processMove(board, "use G39 CoCoCoCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I27 3 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I14 GnGn Wh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Red PnPn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use I08 Wh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 3 PLAINS");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S06 4 3 CoCoMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I37 2 2");
    MoveProcessor.processMove(board, "use I37 Bo");
    MoveProcessor.processMove(board, "buy_district 3 PLAINS");
    MoveProcessor.processMove(board, "buy_plot 1 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Green PnPn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "use I24 PnBeWhBeWhBeWh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Green PnPn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use I27");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S07 1 1 CoCoCoShShShShShShShHo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I20 2 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G18 ClClClSnCoWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I40 3 2");
    MoveProcessor.processMove(board, "use I40 *");
    MoveProcessor.processMove(board, "use I35 PnPnPnPnPnWhOrOrOrBo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert PnPnPnPnPn");
    MoveProcessor.processMove(board, "use I30 MtMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S08 4 3 MtMtMtMtMtMtCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S06 2 3 BeSwSwSwSwSwSwWoWoWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 3 1 ShShHoHoHo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 3 3 BeSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S07 3 3 CoCoCoMtMtShShHo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 4 3 BeBe");
    MoveProcessor.processMove(board, "commit");
  }

  @Test
  public void testEndingScores() throws WeblaboraException {
    assertThat(board.isGameOver(), is(true));
  }
}
