package com.philihp.weblabora.model;

import com.google.common.collect.ImmutableMap;
import com.philihp.weblabora.model.Scorecard.PlayerScore;
import com.philihp.weblabora.model.building.*;
import org.junit.Before;
import org.junit.Test;

import java.util.Map;
import java.util.Map.Entry;

import static org.hamcrest.Matchers.*;
import static org.junit.Assert.assertThat;

/**
 * Runs through game 53955 and checks ending board.
 */
public class Game29696Test {

  Board board;

  @Before
  public void setUp() throws Exception {
    board = new Board();
    MoveProcessor.processMove(board, "config PLAYERS 4");
    MoveProcessor.processMove(board, "config LENGTH LONG");
    MoveProcessor.processMove(board, "config COUNTRY FRANCE");
    MoveProcessor.processMove(board, "start");
    MoveProcessor.processMove(board, "use LR3 Jo");
    MoveProcessor.processMove(board, "buy_district 2 HILLS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G01 3 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG3");
    MoveProcessor.processMove(board, "buy_district -1 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G07 0 0 Cl");
    MoveProcessor.processMove(board, "use G07 PtPtPt *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build F03 3 0");
    MoveProcessor.processMove(board, "use F03");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "use F03");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB1 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 2 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G02 3 1");
    MoveProcessor.processMove(board, "use G02 PtClPn Gn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G02 ClGnSh Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build F05 2 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build G06 3 0 SwCl");
    MoveProcessor.processMove(board, "use G06 CoCoCo *");
    MoveProcessor.processMove(board, "buy_plot 0 MOUNTAIN");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F04 4 2");
    MoveProcessor.processMove(board, "use F04 GnGnGnGnGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "use F04 GnGnGnGnGnGnGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1 Jo");
    MoveProcessor.processMove(board, "buy_district 2 HILLS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F05 FlFlFlFlFlSwSwSwSwSwBrBr");
    MoveProcessor.processMove(board, "buy_district 3 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G07 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G07 PtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 3 0 ShShShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 3 1 ShShCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 2 3 BrBrPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 3 -1 PnShCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 2 HILLS");
    MoveProcessor.processMove(board, "use LB1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Sh");
    MoveProcessor.processMove(board, "buy_district 3 HILLS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 1 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G13 0 0");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract F04 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use F04 GnGnGnGnGnGnGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F09 3 1");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use F03");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract F05 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use F05 FlFlFlFlFlFlFlSwSwSwSwSwSwSwBrBr");
    MoveProcessor.processMove(board, "buy_district -2 HILLS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G16 4 2");
    MoveProcessor.processMove(board, "use G16 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGnGnGn");
    MoveProcessor.processMove(board, "build G19 0 1 WoWoClCl");
    MoveProcessor.processMove(board, "use G19 SwSwSwSwShShShSh *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use F03");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG3");
    MoveProcessor.processMove(board, "buy_plot -2 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G07 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G07 PtPtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F04 GnGnGnGnGnGnGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S04 -1 -1 BrBrBrCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 3 2 ShGnCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 4 2 MtSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 1 2 BrPtWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract LR3 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use LR3 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F23 3 0");
    MoveProcessor.processMove(board, "use F23 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract F05 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use F05 FlFlFlFlFlFlFlCoSwBrBr");
    MoveProcessor.processMove(board, "buy_district 3 HILLS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 2 2 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F14 4 3");
    MoveProcessor.processMove(board, "use F14");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G12 4 -2");
    MoveProcessor.processMove(board, "use G12 BrBrCo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G02 SwWoGn Wo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G18 5 1 WoWoWo");
    MoveProcessor.processMove(board, "use G18 ClClPt *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F10 0 1");
    MoveProcessor.processMove(board, "use F10 2 2 *");
    MoveProcessor.processMove(board, "build F25 2 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G07 PtPtPtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F21 1 1");
    MoveProcessor.processMove(board, "use F21 GpGpGpGpGpGp Wn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB3");
    MoveProcessor.processMove(board, "buy_plot 1 MOUNTAIN");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G06 CoCoCo");
    MoveProcessor.processMove(board, "buy_plot 2 MOUNTAIN");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F05 FlFlFlFlFlFlFlWoSwSwSwSwSwBrBr");
    MoveProcessor.processMove(board, "buy_plot 1 MOUNTAIN");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "use F10 2 0");
    MoveProcessor.processMove(board, "build F15 2 -1");
    MoveProcessor.processMove(board, "use F15 Pn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G02 WoSwGn Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Ni");
    MoveProcessor.processMove(board, "build G22 6 2 PnPnPnPnPn");
    MoveProcessor.processMove(board, "use G22 Jo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 0 -1");
    MoveProcessor.processMove(board, "fell_trees 2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F14");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F23 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G01 PnPn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "use G22");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 2 2 CoCoMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S01 5 2 GnPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 1 -1 BrGnGnWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 3 3 WoBrSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F08 3 2 SnSn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F21 GpGpGpGpGp Wn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build F30 0 -1");
    MoveProcessor.processMove(board, "use F30 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot 2 COAST");
    MoveProcessor.processMove(board, "build F11 -1 2");
    MoveProcessor.processMove(board, "use F11 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F05 BrBr");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G13 PnPn");
    MoveProcessor.processMove(board, "buy_plot 0 MOUNTAIN");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G22 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F27 5 1");
    MoveProcessor.processMove(board, "use F27");
    MoveProcessor.processMove(board, "use G22");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F32 5 1");
    MoveProcessor.processMove(board, "use F32 Pn *");
    MoveProcessor.processMove(board, "cut_peat 0 -2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract F15 PnPn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use F15 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build F17 5 2 SnSnSw");
    MoveProcessor.processMove(board, "use F17 PnPn Bo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "use F17 PnPnPn Bo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S04 -1 3 CoShShShSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGn");
    MoveProcessor.processMove(board, "settle S05 3 3 SwSwMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 3 3 PtPtPtShBr");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 2 0 MtCoCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G16");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F24 3 2");
    MoveProcessor.processMove(board, "use F24 BrBrWnWn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F31 3 -2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G41 4 3");
    MoveProcessor.processMove(board, "use G41 PnPnPnPnPn PoPoBo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 2 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use LR2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G22 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G22");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F25 WoClSnSwPtGnShFlGpBoPoWnBr");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build F40 5 3 WoWoWoSw");
    MoveProcessor.processMove(board, "use F40 *");
    MoveProcessor.processMove(board, "use F38 1 0 1 1 1 2 1 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGn");
    MoveProcessor.processMove(board, "work_contract F10 PnPn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use F10 0 3");
    MoveProcessor.processMove(board, "build F20 1 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F38 4 -1");
    MoveProcessor.processMove(board, "use F38 1 -2 2 -2 1 0 1 1 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G16");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LW2 GnJo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 0 3 Jo");
    MoveProcessor.processMove(board, "use F04 GnGnGnGnGnGnGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G39 1 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F25 WoClSwPnPtGnShFlGpBoPoBrCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F05 FlFlFlFlFlFlFlSwSwSwSwSwSwSwBrBr");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F23 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGnGnGn");
    MoveProcessor.processMove(board, "use G19 SwSwSwSwShShShSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use F24 BrBrWnWn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G26 -1 -2");
    MoveProcessor.processMove(board, "use G26 WoWo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 2 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G18 ClClClSnCoWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F36 0 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "use G26 WoWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGn");
    MoveProcessor.processMove(board, "build F37 5 1");
    MoveProcessor.processMove(board, "use F37 WoWoWoSwSwSw *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G16 Wn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G16");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use F24 BrBrWnWn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F36 Or Or *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F23 Pn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "use F25 WoClSnPnPtGnSwShCoBoPoOrMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 0 3 WoBrGpGp");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S07 2 -2 WoPtPtPtPtGpGpFlFlGnNiNi");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S07 2 3 CoCoWoWoWoBrBrBrShShSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S08 4 3 PtWoMtMtMtMtMtShShPn");
    MoveProcessor.processMove(board, "commit");
  }

  @Test
  public void testEndingScores() throws WeblaboraException {
    assertThat(board.isGameOver(), is(true));
  }
}
