package com.philihp.weblabora.model;

import com.google.common.collect.ImmutableMap;
import com.philihp.weblabora.model.Scorecard.PlayerScore;
import com.philihp.weblabora.model.building.*;
import org.junit.Before;
import org.junit.Test;

import java.util.Map;
import java.util.Map.Entry;

import static org.hamcrest.Matchers.*;
import static org.junit.Assert.assertThat;

/**
 * Runs through game 53955 and checks ending board.
 */
public class Game53626Test {

  Board board;

  @Before
  public void setUp() throws Exception {
    board = new Board();
    MoveProcessor.processMove(board, "config PLAYERS 3");
    MoveProcessor.processMove(board, "config LENGTH LONG");
    MoveProcessor.processMove(board, "config COUNTRY FRANCE");
    MoveProcessor.processMove(board, "start");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build G06 3 0");
    MoveProcessor.processMove(board, "use G06 PtWo *");
    MoveProcessor.processMove(board, "buy_district 2 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees1 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR3");
    MoveProcessor.processMove(board, "buy_plot 1 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G01 3 1");
    MoveProcessor.processMove(board, "use G01 *");
    MoveProcessor.processMove(board, "use G06 PtPtPt");
    MoveProcessor.processMove(board, "buy_district 2 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F09 3 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 Gn");
    MoveProcessor.processMove(board, "buy_plot 1 MOUNTAIN");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG1 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB3");
    MoveProcessor.processMove(board, "buy_district 2 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees0 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract RED Pn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use LR2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G12 3 0");
    MoveProcessor.processMove(board, "use G12 PtShSh *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 ShJo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G02 3 2");
    MoveProcessor.processMove(board, "use G02 WoClPn Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG3");
    MoveProcessor.processMove(board, "buy_plot 1 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 2 2 ShShPtWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 2 2 ShShShSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 1 2 ShShShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build G16 3 1");
    MoveProcessor.processMove(board, "use G16 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use G02 GpClWo Wo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "use G16");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F08 1 2");
    MoveProcessor.processMove(board, "use F08 WoClGnSh");
    MoveProcessor.processMove(board, "buy_district 3 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F04 -1 1");
    MoveProcessor.processMove(board, "use F04 GnGnGnGnGnGn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract RED Pn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use F04 GnGnGnGnGnGnGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F14 4 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F05 1 2");
    MoveProcessor.processMove(board, "use F05 WoWoWoFlFlFlFlFlFl BrBr");
    MoveProcessor.processMove(board, "buy_plot 1 MOUNTAIN");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB3");
    MoveProcessor.processMove(board, "buy_plot 0 MOUNTAIN");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G07 5 1");
    MoveProcessor.processMove(board, "use G07 PtPtPtPtPtPt *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G16");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use LR2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "use F05 FlFlFlFlFlFlFlCoSw BrBr");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G16");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S04 -1 2 BrBrShCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 3 3 ShShBr");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 0 1 WoShBr");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G22 6 1");
    MoveProcessor.processMove(board, "use G22 Jo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB1");
    MoveProcessor.processMove(board, "buy_plot 2 MOUNTAIN");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use G02 WoClSw Cl");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F21 2 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "use F08 ClGnSwPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "use F08 GnSwClPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees0 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract BLUE PnPn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use F14");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG3");
    MoveProcessor.processMove(board, "buy_district 3 HILLS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G12 PtPtPtShShShBrPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G22 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract GREEN PnPn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use F21 GpGpGpGpGpGpGpGp Wn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F11 -1 1");
    MoveProcessor.processMove(board, "use F11 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 4 2 ShShPnPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S04 -1 2 BrBrBrPtWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 0 1 ShBrCoCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F29 6 0");
    MoveProcessor.processMove(board, "use F29 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract GREEN Wn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G07 PtPtPtPtPtPtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F32 3 0");
    MoveProcessor.processMove(board, "use F32 Pn");
    MoveProcessor.processMove(board, "cut_peat 0 3");
    MoveProcessor.processMove(board, "fell_trees0 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G16");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_plot 3 COAST");
    MoveProcessor.processMove(board, "build F33 -1 3");
    MoveProcessor.processMove(board, "use F33 Co Mt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F24 3 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract BLUE Wn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use F14");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F17 4 2");
    MoveProcessor.processMove(board, "use F17 PnPnPn Bo *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G16");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use G06 CoCoCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F30 0 2");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Green PnPn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use F32 Pn");
    MoveProcessor.processMove(board, "cut_peat 0 0");
    MoveProcessor.processMove(board, "fell_trees1 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract GREEN Wn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use F21 GpGpGpGpGp Wn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract RED Wn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use F33 Co Mt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract BLUE Wn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use F29");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F11");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract Green PnPn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G07 PtPtPtPtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F27 5 2");
    MoveProcessor.processMove(board, "use F27 Wn *");
    MoveProcessor.processMove(board, "use F11");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 3 2 WoMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S01 1 1 WoPn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S07 0 2 MtMtMtCoCoCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build F40 4 3");
    MoveProcessor.processMove(board, "use F40 *");
    MoveProcessor.processMove(board, "use F38 1 0 2 0 1 1 1 3 2 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F09");
    MoveProcessor.processMove(board, "use LR3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F36 1 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G19 0 0");
    MoveProcessor.processMove(board, "use G19 GnGnGnGnGnGnGnGnGnShShShShShShShShSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "buy_district 3 HILLS");
    MoveProcessor.processMove(board, "use F33 Co Mt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F40");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S02 0 3 BrCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F08 WoClShCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F38 0 0");
    MoveProcessor.processMove(board, "use F38 1 0 1 1 1 3 2 3 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGn");
    MoveProcessor.processMove(board, "build F20 1 1");
    MoveProcessor.processMove(board, "use F20 BrBrWn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G28 6 2");
    MoveProcessor.processMove(board, "use G28 *");
    MoveProcessor.processMove(board, "settle S08 5 2 MtMtMtMtMtMtCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract GREEN Wn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use G01");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S06 1 1 CoCoMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build F35 0 0");
    MoveProcessor.processMove(board, "use F35 Ni *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Ni");
    MoveProcessor.processMove(board, "work_contract Green PnPn");
    MoveProcessor.processMove(board, "with CLERGYMAN");
    MoveProcessor.processMove(board, "use F17 PnPnPn Bo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build F37 3 3");
    MoveProcessor.processMove(board, "use F37 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G16");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G34 2 3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G07 PtPtPtPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F24 BrWn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use F17 PnPnPn Bo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S07 2 3 CoCoCoMtMtMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G28");
    MoveProcessor.processMove(board, "settle S06 5 3 CoCoMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGnGnGn");
    MoveProcessor.processMove(board, "settle S08 4 2 SwSwSwSwSwSwGnGnShShShShMtMtMtMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S08 3 3 ShShShShShShPnPnPnNiNiNiCo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S07 2 3 MtMtMtCoCoCo");
    MoveProcessor.processMove(board, "commit");
  }

  @Test
  public void testEndingScores() throws WeblaboraException {
    assertThat(board.isGameOver(), is(true));
  }
}
