package com.philihp.weblabora.model;

import com.google.common.collect.ImmutableMap;
import com.philihp.weblabora.model.Scorecard.PlayerScore;
import com.philihp.weblabora.model.building.*;
import org.junit.Before;
import org.junit.Test;

import java.util.Map;
import java.util.Map.Entry;

import static org.hamcrest.Matchers.*;
import static org.junit.Assert.assertThat;

/**
 * Runs through game 53955 and checks ending board.
 */
public class Game44462Test {

  Board board;

  @Before
  public void setUp() throws Exception {
    board = new Board();
    MoveProcessor.processMove(board, "config PLAYERS 3");
    MoveProcessor.processMove(board, "config LENGTH SHORT");
    MoveProcessor.processMove(board, "config COUNTRY IRELAND");
    MoveProcessor.processMove(board, "start");
    MoveProcessor.processMove(board, "fell_trees 2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 1 1 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G02 3 1");
    MoveProcessor.processMove(board, "use G02 GnShCl Sh *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G12 2 0");
    MoveProcessor.processMove(board, "use G12 ShWo Sn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR3 Pn");
    MoveProcessor.processMove(board, "buy_plot 0 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract LG3 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use LG2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I08 -1 0");
    MoveProcessor.processMove(board, "use I08 Be *");
    MoveProcessor.processMove(board, "buy_district -1 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 3 0 ShShShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 3 0 ShShShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S04 -1 1 BeShGnWoPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract G12 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use G12 ShShPt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I14 0 0");
    MoveProcessor.processMove(board, "use I14 HoHo Be *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR3 Pn");
    MoveProcessor.processMove(board, "buy_district -1 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract I14 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use I14 HoHo Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G02 GnPtSh Pn");
    MoveProcessor.processMove(board, "buy_district 2 PLAINS");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract I08 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use I08 Wh");
    MoveProcessor.processMove(board, "buy_plot 0 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 1 1 BePt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 0 1 WoShGnGnGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S05 1 0 BePt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build I05 0 1");
    MoveProcessor.processMove(board, "use I05 GnHoGnHo BePnPnPnPnPnPnPn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build I17 3 2");
    MoveProcessor.processMove(board, "use I17 Pn *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract I14 Pn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use I14 HoHo Wh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I24 3 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGn");
    MoveProcessor.processMove(board, "build I21 1 0");
    MoveProcessor.processMove(board, "use I21 HoWoPtHoWoPt *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G18 2 2");
    MoveProcessor.processMove(board, "use G18 ClSnPt *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 2 -1 PtPtPtShGnGnGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 0 0 PtPtPtShShPn ");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S06 0 0 PtPtPtMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert Gn");
    MoveProcessor.processMove(board, "build I33 1 -1");
    MoveProcessor.processMove(board, "use I33 WoWoWo Be *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I05 PnPnPnPnPnPnPn Be");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "cut_peat 0 1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 2 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I30 1 2");
    MoveProcessor.processMove(board, "use I30 Mt *");
    MoveProcessor.processMove(board, "buy_plot 0 COAST");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I14 GnGn Wh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I27 3 0");
    MoveProcessor.processMove(board, "use I27 Wh *");
    MoveProcessor.processMove(board, "use I30 Mt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S04 -1 1 PtWoBeShGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S07 0 1 PtPtPtPtWoBeBeBe");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S03 3 1 BeSh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB1");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I24 PnBeWhBeWh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LG2 Gn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "fell_trees 1 1 Jo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G26 -1 0");
    MoveProcessor.processMove(board, "use G26 WoWo");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I04 2 -1");
    MoveProcessor.processMove(board, "use I04 GnGnGnGn");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LB3");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use G02 GnPnCl Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use I05 GnHoGnHoGnHoGnHo PnPnPnPnPnPnPnBe");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I37 -1 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I38 3 -1");
    MoveProcessor.processMove(board, "use I38 *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "work_contract I24 PnPn");
    MoveProcessor.processMove(board, "with LAYBROTHER");
    MoveProcessor.processMove(board, "use I24 PnBeWhBeWhBeWh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build G41 1 1");
    MoveProcessor.processMove(board, "use G41 PnPnPnPnPn RqOr *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "use LR2 Sh");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "build I35 4 -1");
    MoveProcessor.processMove(board, "use I35 NiWhBoBoBoRq *");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "convert GnGn");
    MoveProcessor.processMove(board, "build G34 1 0");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S08 4 -1 WoPtShShShShShShShShShShShShShShMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S02 3 -1 WoWoWoMt");
    MoveProcessor.processMove(board, "commit");
    MoveProcessor.processMove(board, "settle S08 4 2 WoWoWoMtBeShShShShShShShShGnGnPnPn");
    MoveProcessor.processMove(board, "commit");
  }

  @Test
  public void testEndingScores() throws WeblaboraException {
    assertThat(board.isGameOver(), is(true));
  }
}
