DROP TABLE IF EXISTS `SEQUENCE`;
CREATE TABLE `SEQUENCE` (
  `SEQ_NAME` varchar(50) NOT NULL PRIMARY KEY,
  `SEQ_COUNT` decimal(38,0) DEFAULT NULL,
);

INSERT INTO `SEQUENCE` VALUES (`SEQ_GEN`, 9000);
